# TCL File Generated by Component Editor 15.0
# Thu Dec 15 11:23:15 CET 2016
# DO NOT MODIFY


# 
# RFReceive "RFRec" v1.0
# JW Zhang 2016.12.15.11:23:15
# RF Receive Function
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module RFReceive
# 
set_module_property DESCRIPTION "RF Receive Function"
set_module_property NAME RFReceive
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP MyriadRFPorject
set_module_property AUTHOR "JW Zhang"
set_module_property DISPLAY_NAME RFRec
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL RFReceive
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file RFReceive.vhd VHDL PATH RFReceive.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point conduit
# 
add_interface conduit conduit end
set_interface_property conduit associatedClock clock
set_interface_property conduit associatedReset ""
set_interface_property conduit ENABLED true
set_interface_property conduit EXPORT_OF ""
set_interface_property conduit PORT_NAME_MAP ""
set_interface_property conduit CMSIS_SVD_VARIABLES ""
set_interface_property conduit SVD_ADDRESS_GROUP ""

add_interface_port conduit RXCLK rxclock Input 1
add_interface_port conduit RXD rxdata Input 12
add_interface_port conduit RXEN rxenable Output 1
add_interface_port conduit RXIQSEL rxiq Input 1
add_interface_port conduit RecEnable recen Input 1
add_interface_port conduit LED testled Output 4


# 
# connection point IDataFIFO
# 
add_interface IDataFIFO avalon_streaming start
set_interface_property IDataFIFO associatedClock IDataFIFOCLK
set_interface_property IDataFIFO associatedReset reset
set_interface_property IDataFIFO dataBitsPerSymbol 8
set_interface_property IDataFIFO errorDescriptor ""
set_interface_property IDataFIFO firstSymbolInHighOrderBits true
set_interface_property IDataFIFO maxChannel 0
set_interface_property IDataFIFO readyLatency 0
set_interface_property IDataFIFO ENABLED true
set_interface_property IDataFIFO EXPORT_OF ""
set_interface_property IDataFIFO PORT_NAME_MAP ""
set_interface_property IDataFIFO CMSIS_SVD_VARIABLES ""
set_interface_property IDataFIFO SVD_ADDRESS_GROUP ""

add_interface_port IDataFIFO rfRec_i_data data Output 16
add_interface_port IDataFIFO rfRec_i_ready ready Input 1
add_interface_port IDataFIFO rfRec_i_valid valid Output 1


# 
# connection point QDataFIFO
# 
add_interface QDataFIFO avalon_streaming start
set_interface_property QDataFIFO associatedClock QDataFIFOCLK
set_interface_property QDataFIFO associatedReset reset
set_interface_property QDataFIFO dataBitsPerSymbol 8
set_interface_property QDataFIFO errorDescriptor ""
set_interface_property QDataFIFO firstSymbolInHighOrderBits true
set_interface_property QDataFIFO maxChannel 0
set_interface_property QDataFIFO readyLatency 0
set_interface_property QDataFIFO ENABLED true
set_interface_property QDataFIFO EXPORT_OF ""
set_interface_property QDataFIFO PORT_NAME_MAP ""
set_interface_property QDataFIFO CMSIS_SVD_VARIABLES ""
set_interface_property QDataFIFO SVD_ADDRESS_GROUP ""

add_interface_port QDataFIFO rfRec_q_data data Output 16
add_interface_port QDataFIFO rfRec_q_ready ready Input 1
add_interface_port QDataFIFO rfRec_q_valid valid Output 1


# 
# connection point IDataFIFOCLK
# 
add_interface IDataFIFOCLK clock start
set_interface_property IDataFIFOCLK associatedDirectClock ""
set_interface_property IDataFIFOCLK clockRate 0
set_interface_property IDataFIFOCLK clockRateKnown false
set_interface_property IDataFIFOCLK ENABLED true
set_interface_property IDataFIFOCLK EXPORT_OF ""
set_interface_property IDataFIFOCLK PORT_NAME_MAP ""
set_interface_property IDataFIFOCLK CMSIS_SVD_VARIABLES ""
set_interface_property IDataFIFOCLK SVD_ADDRESS_GROUP ""

add_interface_port IDataFIFOCLK rfRec_i_clk clk Output 1


# 
# connection point QDataFIFOCLK
# 
add_interface QDataFIFOCLK clock start
set_interface_property QDataFIFOCLK associatedDirectClock ""
set_interface_property QDataFIFOCLK clockRate 0
set_interface_property QDataFIFOCLK clockRateKnown false
set_interface_property QDataFIFOCLK ENABLED true
set_interface_property QDataFIFOCLK EXPORT_OF ""
set_interface_property QDataFIFOCLK PORT_NAME_MAP ""
set_interface_property QDataFIFOCLK CMSIS_SVD_VARIABLES ""
set_interface_property QDataFIFOCLK SVD_ADDRESS_GROUP ""

add_interface_port QDataFIFOCLK rfRec_q_clk clk Output 1

