# TCL File Generated by Component Editor 15.0
# Wed Nov 30 10:04:35 CET 2016
# DO NOT MODIFY


# 
# recCtrl "recCtrl" v1.0
# JW Zhang 2016.11.30.10:04:35
# RF Receive Control
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module recCtrl
# 
set_module_property DESCRIPTION "RF Receive Control"
set_module_property NAME recCtrl
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP MyriadRFPorject
set_module_property AUTHOR "JW Zhang"
set_module_property DISPLAY_NAME recCtrl
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL recCtrl
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file recCtrl.vhd VHDL PATH recCtrl.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point conduit
# 
add_interface conduit conduit end
set_interface_property conduit associatedClock clock
set_interface_property conduit associatedReset ""
set_interface_property conduit ENABLED true
set_interface_property conduit EXPORT_OF ""
set_interface_property conduit PORT_NAME_MAP ""
set_interface_property conduit CMSIS_SVD_VARIABLES ""
set_interface_property conduit SVD_ADDRESS_GROUP ""

add_interface_port conduit RecEnable enrec Output 1


# 
# connection point recCtrlMM
# 
add_interface recCtrlMM avalon end
set_interface_property recCtrlMM addressUnits WORDS
set_interface_property recCtrlMM associatedClock clock
set_interface_property recCtrlMM associatedReset reset
set_interface_property recCtrlMM bitsPerSymbol 8
set_interface_property recCtrlMM burstOnBurstBoundariesOnly false
set_interface_property recCtrlMM burstcountUnits WORDS
set_interface_property recCtrlMM explicitAddressSpan 0
set_interface_property recCtrlMM holdTime 0
set_interface_property recCtrlMM linewrapBursts false
set_interface_property recCtrlMM maximumPendingReadTransactions 0
set_interface_property recCtrlMM maximumPendingWriteTransactions 0
set_interface_property recCtrlMM readLatency 0
set_interface_property recCtrlMM readWaitTime 1
set_interface_property recCtrlMM setupTime 0
set_interface_property recCtrlMM timingUnits Cycles
set_interface_property recCtrlMM writeWaitTime 0
set_interface_property recCtrlMM ENABLED true
set_interface_property recCtrlMM EXPORT_OF ""
set_interface_property recCtrlMM PORT_NAME_MAP ""
set_interface_property recCtrlMM CMSIS_SVD_VARIABLES ""
set_interface_property recCtrlMM SVD_ADDRESS_GROUP ""

add_interface_port recCtrlMM write_data writedata Input 8
add_interface_port recCtrlMM write_en write Input 1
set_interface_assignment recCtrlMM embeddedsw.configuration.isFlash 0
set_interface_assignment recCtrlMM embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment recCtrlMM embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment recCtrlMM embeddedsw.configuration.isPrintableDevice 0

